# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Beginner's Luck
tagline:          'Personal Website'
description:      ''
url:              http://poochi.github.com
baseurl:          '/'
paginate:         5

author:
  name:           'Gowtham Rangarajan'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poochi
